# Generated by Django 5.1.4 on 2025-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('video_url', models.URLField()),
                ('video_id', models.CharField(max_length=50)),
            ],
        ),
    ]
