# Generated by Django 5.1.4 on 2025-01-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
