# Generated by Django 5.1.4 on 2025-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0003_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(max_length=2048)),
                ('video_url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
