# Generated by Django 5.1.4 on 2025-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0004_game_delete_image_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(max_length=2048),
        ),
    ]
