# Generated by Django 5.1.4 on 2025-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0006_alter_game_image_url_alter_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='section',
            field=models.CharField(choices=[('featured', 'Featured'), ('trending', 'Trending')], default='featured', max_length=10),
        ),
    ]
