# Generated by Django 5.1.4 on 2025-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0007_game_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='section',
            field=models.CharField(choices=[('featured', 'Featured'), ('trending', 'Trending'), ('new', 'New Released'), ('free', 'Free Games'), ('popular', 'Popular Games')], default='featured', max_length=10),
        ),
    ]
