# Generated by Django 5.1.4 on 2025-01-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0013_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
