# Generated by Django 5.1.4 on 2025-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHunt', '0018_remove_cartitem_quantity_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'game')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'game'], name='GameHunt_ca_cart_id_1862a5_idx'),
        ),
    ]
